@startuml test
skinparam style strictuml
skinparam sequenceMessageAlign center
title Check In

Actor "User/Check" as user

participant ":CheckInCommand" as CIC
participant ":MainViewModel" as MVM
participant ":UserViewModel" as UVM
participant ":UserRepository" as UR
participant ":FileHandler" as FH

user -> CIC ++: Execute()
    
    CIC -> MVM ++: UserCheckIn(UserName)      

        MVM -> UVM ++: CheckUser(UserName)

            UVM -> UR ++: CheckUser(UserName)

            return "User:User"

        return "User:User"

        MVM ->  UVM ++: UserCheckIn(User:User)
            UVM -> UR ++: UserCheckIn(User:User)
                UR -> FH ++: WriteToFile(User:User)

                return "log file updated"

            return "user checked in"

         return "user checked in"
    return "user checked in"
return "you have been checked in"