@startuml test
skinparam style strictuml
skinparam sequenceMessageAlign center
title Check Out

Actor "User/Check" as user

participant ":CheckOutCommand" as COC
participant ":MainViewModel" as MVM
participant ":UserViewModel" as UVM
participant ":UserRepository" as UR
participant ":FileHandler" as FH

user -> COC ++: Execute()
    
    COC -> MVM ++: UserCheckOut(UserName)      

        MVM -> UVM ++: CheckUser(UserName)

            UVM -> UR ++: CheckUser(UserName)

            return "User:User"

        return "User:User"

        MVM ->  UVM ++: UserCheckOut(User:User)
            UVM -> UR ++: UserCheckOut(User:User)
                UR -> FH ++: WriteToFile(User:User)

                return "log file updated"

            return "user checked out"

         return "user checked out"
    return "user checked out"
return "you have been checked out"