@startuml test
skinparam style strictuml
skinparam sequenceMessageAlign center
title Check

Actor "User/AdminMenu" as user

participant ":UpdateColourCommand" as UCC
participant ":MainViewModel" as MVM
participant ":ColorViewModel" as CVM
participant ":ImageViewModel" as IVM


user -> UCC ++: Execute(string : ID)
return Display MessageBox Confirm action

user -> UCC ++: Confirm
UCC -> UCC : Check(ID)
UCC -> MVM ++: Update Colour and Image
MVM -> CVM ++: Update Colour
return 
MVM -> IVM ++: Update Image
return
return
UCC -> UCC : Update ColourFiles
UCC -> UCC : update ImageFiles
return Display Default Colors and Images