@startuml test
skinparam style strictuml
skinparam sequenceMessageAlign center
title UpdateColour

Actor "User/AdminMenu" as user

participant ":UpdateColourCommand" as UCC
participant ":MainViewModel" as MVM
participant ":ColourRepository" as CRP
participant ":ColourViewModel" as CVM


user -> UCC ++: Execute(string : ID)
UCC -> MVM ++: Execute(string : ID)
MVM -> CRP ++: Update(ID)
CRP ---> user: Display Colorpicker
user ---> CRP : SelectedColour : string
return Update ColourViewModel
return
return Display new colour


