@startuml test
skinparam style strictuml
skinparam sequenceMessageAlign center
title Check

Actor "User/AdminMenu" as user

participant ":UpdateImageCommand" as UCC
participant ":MainViewModel" as MVM
participant ":ImageViewModel" as IVM


user -> UCC ++: Execute(string : ID)
return ShowFileDialog()

user -> UCC ++: SelectedImagePath : string
UCC -> UCC : Check(ID)
UCC -> MVM ++: Update ImagePath from ID
MVM -> IVM ++: Update ImagePath
return 
return
UCC -> UCC : Update ImageFiles
return Display Selected Image